# Generated by Django 3.1.6 on 2021-04-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20210403_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='user',
        ),
    ]
