# Generated by Django 3.1.5 on 2021-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20210403_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
