# Generated by Django 3.1.5 on 2021-04-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20210407_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo_link',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
