# Generated by Django 3.1.5 on 2021-04-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20210407_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='first_name',
            field=models.CharField(blank=True, max_length=68),
        ),
        migrations.AddField(
            model_name='manager',
            name='last_name',
            field=models.CharField(blank=True, max_length=68),
        ),
        migrations.AddField(
            model_name='producer',
            name='first_name',
            field=models.CharField(blank=True, max_length=68),
        ),
        migrations.AddField(
            model_name='producer',
            name='last_name',
            field=models.CharField(blank=True, max_length=68),
        ),
    ]
