# Generated by Django 3.1.5 on 2021-04-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0012_auto_20210415_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='service',
            name='producer',
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producer',
            name='first_name',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='producer',
            name='last_name',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
